# Generated by Django 5.0.3 on 2024-03-20 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_rename_users_emailmessage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='room_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
