# Generated by Django 5.0.3 on 2024-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_livereport_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='livereport',
            name='call_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livereport',
            name='stream_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livereport',
            name='video_url',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
