# Generated by Django 5.0.3 on 2024-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_personalinfo_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=255, null=True),
        ),
    ]
