# Generated by Django 4.2.4 on 2023-08-15 15:17

import directory.models
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directory",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=user_profile.models.get_default_profile_image,
                null=True,
                upload_to=directory.models.upload_directory_path,
            ),
        ),
    ]
