# Generated by Django 5.0.3 on 2024-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_directory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
